component_depth: 1
languages:
- java
- perl
- script
exclude:
- ./WEB-INF/.*
- ./bin/.*
- ./bin/META-INF/.*
- ./bin/doc/.*
- ./bin/doc/readme/.*
- ./bin/jsp/.*
- ./bin/net/.*
- ./bin/net/wastl/.*
- ./bin/net/wastl/webmail/.*
- ./bin/net/wastl/webmail/config/.*
- ./bin/net/wastl/webmail/data/.*
- ./bin/net/wastl/webmail/data/xml/.*
- ./bin/net/wastl/webmail/data/xml/de/.*
- ./bin/net/wastl/webmail/data/xml/de/bibop/.*
- ./bin/net/wastl/webmail/data/xml/de/bibop/images/.*
- ./bin/net/wastl/webmail/data/xml/de/classic/.*
- ./bin/net/wastl/webmail/data/xml/de/classic/images/.*
- ./bin/net/wastl/webmail/data/xml/en/.*
- ./bin/net/wastl/webmail/data/xml/en/bibop/.*
- ./bin/net/wastl/webmail/data/xml/en/bibop/images/.*
- ./bin/net/wastl/webmail/data/xml/en/classic/.*
- ./bin/net/wastl/webmail/data/xml/en/classic/images/.*
- ./bin/net/wastl/webmail/data/xml/es/.*
- ./bin/net/wastl/webmail/data/xml/es/bibop/.*
- ./bin/net/wastl/webmail/data/xml/es/bibop/images/.*
- ./bin/net/wastl/webmail/data/xml/es/classic/.*
- ./bin/net/wastl/webmail/data/xml/es/classic/images/.*
- ./bin/net/wastl/webmail/data/xml/fr/.*
- ./bin/net/wastl/webmail/data/xml/fr/bibop/.*
- ./bin/net/wastl/webmail/data/xml/fr/bibop/images/.*
- ./bin/net/wastl/webmail/data/xml/fr/classic/.*
- ./bin/net/wastl/webmail/data/xml/fr/classic/images/.*
- ./bin/net/wastl/webmail/data/xml/hu/.*
- ./bin/net/wastl/webmail/data/xml/hu/bibop/.*
- ./bin/net/wastl/webmail/data/xml/hu/bibop/images/.*
- ./bin/net/wastl/webmail/data/xml/hu/classic/.*
- ./bin/net/wastl/webmail/data/xml/hu/classic/images/.*
- ./bin/net/wastl/webmail/data/xml/zh/.*
- ./bin/net/wastl/webmail/data/xml/zh/bibop/.*
- ./bin/net/wastl/webmail/data/xml/zh/bibop/images/.*
- ./bin/net/wastl/webmail/data/xml/zh/classic/.*
- ./bin/net/wastl/webmail/debug/.*
- ./bin/net/wastl/webmail/exceptions/.*
- ./bin/net/wastl/webmail/logger/.*
- ./bin/net/wastl/webmail/misc/.*
- ./bin/net/wastl/webmail/server/.*
- ./bin/net/wastl/webmail/server/http/.*
- ./bin/net/wastl/webmail/storage/.*
- ./bin/net/wastl/webmail/storage/simple/.*
- ./bin/net/wastl/webmail/ui/.*
- ./bin/net/wastl/webmail/ui/html/.*
- ./bin/net/wastl/webmail/ui/xml/.*
- ./bin/net/wastl/webmail/xml/.*
- ./bin/org/.*
- ./bin/org/bulbul/.*
- ./bin/org/bulbul/webmail/.*
- ./bin/org/bulbul/webmail/util/.*
- ./bin/org/webengruven/.*
- ./bin/org/webengruven/webmail/.*
- ./bin/org/webengruven/webmail/auth/.*
- ./contrib/.*
- ./contrib/bin/.*
- ./contrib/debug/.*
- ./data/.*
- ./data/ssl/.*
- ./data/ssl/certs/.*
- ./lib/.*
